config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :articles
    resources :article_categories
    namespace :blog do
      get :configuration
      post :configuration, as: :configurations
    end
  end
  namespace :blog do
    resources :articles, param: :slug
  end
  get "/blog", to: "articles#index"
end

app/models/concerns/travel_app/config_gem_model.rb
module Concerns::TravelApp::ConfigGemModel
  extend ActiveSupport::Concern
  included do
    attr_accessor :attributes_config
    after_initialize :define_options

    def self.instance_config
      return self.new if first.nil?
      return self.first
    end

    def define_options
      if self.options.nil? || self.options.empty?
        self.options = {}
        self.init_attributes
        @attributes_config.each do |sym|
          self.options[sym] = ""
        end
      end
    end

    def handle_change params
      self.options = params
      self.save
    end

    def type_of_field field
      SpreeBlog.configuration.attributes_config[field.to_sym]
    end
  end
end

app/models/spree/article.rb
class Spree::Article < ApplicationRecord
  include Spree::ResourceMultimediumHelper
  belongs_to :user, foreign_key: 'user_id', class_name: 'Spree::User'
  belongs_to :article_category, foreign_key: 'article_category_id', class_name: 'Spree::ArticleCategory'
  delegate :full_name, to: :user, prefix: 'get_author'
  delegate :name, to: :article_category, prefix: 'get_category'
  before_save :set_slug
  after_save :update_html_content

  def set_slug
    if self.slug.nil?
      self.slug = title.parameterize
    else
      searching = Spree::Article.where(slug: slug).where.not(id: self.id).count
      self.slug = "#{self.slug}-count" if searching > 0
    end
  end

  def update_html_content
    self.update_column(:body_html, regex_tag_for_image(CGI.unescapeHTML(body)))
  end
end

app/models/spree/article_category.rb
class Spree::ArticleCategory < Spree::SpreeGemConfiguration
  table_name_spree :spree_article_categories
end

app/models/spree/article_comment.rb
class Spree::ArticleComment < Spree::Base
  belongs_to :article
  belongs_to :user
end

app/models/spree/blog_configuration.rb
class Spree::BlogConfiguration < ApplicationRecord

  def initialize object
    @attributes_config = SpreeBlog.configuration.attributes
    super
  end

  def init_attributes
    @attributes_config = [:articles_per_page, :is_on]
  end
end

app/controllers/articles_controller.rb
class Spree::ArticlesController < Spree::StoreController
  before_action :set_article, except: :index

  def index
    @articles = Spree::Articles.all
  end

  def show
  end

  private
  def set_article
    @article = Spree::Article.find_by_slug(params[:slug])
  end
end

app/controllers/spree/admin/article_categories_controller.rb
class Spree::Admin::ArticleCategoriesController < Spree::Admin::ResourceController
  before_action :collection, only: :index¿

  create.before :update_author_user

  def index
    session[:return_to] = request.url
    respond_with(@collection)
  end

  def new
    @article_category = Spree::ArticleCategory.new
  end

  def edit
    @article_category = Spree::ArticleCategory.find(params[:id])
  end

  def create
    @article_category = Spree::ArticleCategory.new permitted_resource_params
    invoke_callbacks(:update, :before)
    return render action: :edit unless @article_category.save
    respond_to do |format|
      format.html{
        redirect_to admin_article_categories_url, notice: Spree.t(:article_category_successfully)
      }
    end
  end

  def show
    session[:return_to] ||= request.referer
    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  private
  def collection
    @collection = Spree::ArticleCategory.all
  end
end

app/controllers/spree/admin/articles_controller.rb
class Spree::Admin::ArticlesController < Spree::Admin::ResourceController
  before_action :collection, only: :index
  before_action :collection_articles, only: [:edit, :new]

  create.before :update_author_user

  def index
    session[:return_to] = request.url
    respond_with(@collection)
  end

  def new
    @article = Spree::Article.new
  end

  def edit
    @article = Spree::Article.find(params[:id])
  end

  def create
    @article = Spree::Article.new permitted_resource_params
    @article.user_id = spree_current_user.id
    invoke_callbacks(:update, :before)
    return render action: :edit unless @article.save
    respond_to do |format|
      format.html{
        redirect_to admin_articles_url, notice: Spree.t(:article_successfully)
      }
    end
  end

  def show
    session[:return_to] ||= request.referer
    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  private
  def collection
    @collection = Spree::Article.all
  end

  def update_author_user
    @article.spree_user_id = Spree::User.first.id
    collection_articles
  end

  def collection_articles
    @article_categories = Spree::ArticleCategory.all
  end
end

app/controllers/spree/admin/blog_controller.rb
class Spree::Admin::BlogController < TravelApp::Admin::ConfigGemController
  def initialize
    @model_class = :blog_configuration
    super
  end
end

app/controllers/spree/articles_controller.rb
class Spree::ArticlesController < Spree::BaseGemController
  before_action :set_article, except: :index
  include Spree::ResourceMultimediumHelper

  def initialize
    @model_configuration = :blog_configuration
    super
  end

  def index
    @articles = Spree::Article.all
  end

  private
  def set_article
    @article = Spree::Article.find_by_slug(params[:slug])
  end
end

app/controllers/spree/base_gem_controller.rb
class Spree::BaseGemController < Spree::StoreController
  #before_action :is_gem_active
  attr_reader :model_configuration

  def initialize
    super
  end

  private
  def is_gem_active
    return true #return raise ActionController::RoutingError.new('Not Found') unless eval("Spree::#{@model_configuration.to_s.camelize}.instance_config.options['is_on'] == 'true'")
  end
end

app/controllers/spree/blog/articles_controller.rb
class Spree::Blog::ArticlesController < Spree::BaseGemController
  before_action :set_article, except: :index
  include Spree::ResourceMultimediumHelper

  def initialize
    @model_configuration = :blog_configuration
    super
  end

  def show
  end

  private
  def set_article
    @article = Spree::Article.find_by_slug(params[:slug])
    unless @article.nil?
      body_safe(@article.body)
    end
  end

  def body_safe body
    @body_safe = get_content_safe(body)
  end
end

app/controllers/travel_app/admin/config_gem_controller.rb
class TravelApp::Admin::ConfigGemController < Spree::Admin::ResourceController
  attr_accessor :model_class
  attr_reader :instance_model_config
  before_action :define_configuration, only: [:index, :configuration]

  def index
  end

  def configuration
    if params[:commit] == "send"
      model = instance_config
      if model.handle_change gem_form_attributes
        flash[:success] = "Actualización de la gema realizada con éxito"
      else
        flash[:error] = 'Hubo un error en la actualización de la gema'
      end
      redirect_to action: :configuration
    end
  end

  private
  def instance_config
    @instance_model_config ||= eval("Spree::#{@model_class.to_s.camelize}.instance_config")
    @instance_model_config
  end

  def define_configuration
    session[:return_to] = request.url
    @configuration = instance_config
  end

  def gem_form_attributes
    params[@model_class]["options"]
  end
end

app/views/spree/admin/article_categories/_form.html.erb
<div class="row">
  <div data-hook="admin_articles_form_title">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name), class: 'required' %>
      <%= f.text_field :name, class:'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div data-hook="admin_articles_form_body">
    <%= f.field_container :description, class: ["form-group"] do %>
      <%= f.label :description, Spree.t(:description), class: 'required' %>
      <%= f.text_area :description, {rows: '10', cols:"10", class:'form-control'} %>
      <%= f.error_message_on :description %>
    <% end %>
  </div>
</div>

app/views/spree/admin/article_categories/edit.html.erb
<h1>Editing article category</h1>
<div class="col-12">
  <%= form_for [:admin, @article_category], html: {multipart: true} do |form| %>
    <%= render partial: 'form', locals:{f: form} %>
    <%= form.submit %>
  <% end %>
</div>

app/views/spree/admin/article_categories/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_article_category), new_admin_article_category_url, { class: "btn-success", icon: 'add', id: 'admin_new_article' } %>
<% end if can?(:create, Spree::ArticleCategory) %>
<table class="table" id="listing_articles">
  <thead>
    <tr data-hook="admin_blog_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:description) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @collection.each do |article_category| %>
      <tr>
        <td><%= article_category.name %></td>
        <td><%= article_category.description %></td>
        <td class="actions actions-3 text-right">
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/article_categories/new.html.erb
<h1>Creating article category</h1>
<div class="col-12">
  <%= form_for [:admin, @article_category], html: {multipart: true} do |form| %>
    <%= render partial: 'form', locals:{f: form} %>
    <%= form.submit %>
  <% end %>
</div>

app/views/spree/admin/article_categories/show.html.erb
<h1>Detail Article</h1>

app/views/spree/admin/articles/_form.html.erb
<div class="row">
  <div data-hook="admin_articles_form_title">
    <%= f.field_container :title, class: ['form-group'] do %>
      <%= f.label :title, Spree.t(:title), class: 'required' %>
      <%= f.text_field :title, class:'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div data-hook="admin_articles_form_body">
    <%= f.field_container :body, class: ["form-group"] do %>
      <%= f.label :body, Spree.t(:body), class: 'required' %>
      <%= f.text_area :body, {rows: '10', cols:"10", class:'form-control'} %>
      <%= f.error_message_on :body %>
    <% end %>
  </div>
  <div id="example"></div>

  <div data-hook="admin_articles_form_category">
    <%= f.field_container :article_categories, class: ["form-group"] do %>
      <%= f.label :article_category_id, Spree.t(:article_category), class: 'required' %>
      <%= f.collection_select(:article_category_id, @article_categories, :id, :name, {included_blank: Spree.t(:select_article_category_blank)}) %>
    <% end %>
  </div>
</div>
<% content_for :extrajs do %>
<script type="text/javascript">
  var editor = new FroalaEditor('#article_body', {
    imageManagerLoadURL: "<%= api_multimedia_all_files_path(token: spree_current_user.spree_api_key) %>"
  });
</script>
<% end %>

app/views/spree/admin/articles/_menu_options_blog.html.erb
<ul class="nav nav-sidebar">
  <li class="sidebar-menu-item"><a data-toggle="collapse" data-parent="#sidebar" href="#sidebar-configuration-blog"><span class="icon icon-wrench"></span><span class="text">Blog</span><span class="icon icon-chevron-left pull-right"></span></a>
    <ul data-hook="admin_configurations_sidebar_menu" class="collapse nav nav-pills nav-stacked" id="sidebar-configuration-blog">
      <%= tab Spree::BlogConfiguration, url: admin_blog_configuration_path, icon: "file", label: "Configuración" %>
      <%= tab Spree::Article, url: admin_articles_path, icon: "file", label: "Artículos" %>
      <%= tab Spree::ArticleCategory, url: admin_article_categories_path, icon: "file", label: "Categoría de artículos" %>
    </ul>
  </li>
</ul>

app/views/spree/admin/articles/edit.html.erb
<h1>Editing article</h1>
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item active">
    <a class="nav-link active" data-toggle="tab" href="#form" aria-selected="true">Formulario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#multimedia" aria-selected="false">Multimedia</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade fade in active" id="form" role="tabpanel" aria-labelledby="form-tab">
    <div class="col-12">
      <%= form_for [:admin, @article], html: {multipart: true} do |form| %>
      <%= render partial: 'form', locals:{f: form} %>
      <%= form.submit %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="multimedia" role="tabpanel" aria-labelledby="multimedia-tab">
    <div class="col-12">
      <%= render partial: "spree/multimedia/widgets/form_multimedia_upload" %>
    </div>
  </div>
</div>

app/views/spree/admin/articles/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_article), new_admin_article_url, { class: "btn-success", icon: 'add', id: 'admin_new_article' } %>
<% end if can?(:create, Spree::Article) %>
<table class="table" id="listing_articles">
  <thead>
    <tr data-hook="admin_blog_index_headers">
      <th><%= Spree.t(:title) %></th>
      <th><%= Spree.t(:created_by) %></th>
      <th><%= Spree.t(:article_available_on) %></th>
      <th><%= Spree.t(:category) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @collection.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.get_author_full_name %></td>
        <td><%= article.available_on %></td>
        <td><%= article.get_category_name %></td>
        <td class="actions actions-3 text-right">
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/articles/new.html.erb
<h1>Creating article</h1>
<div class="col-12">
  <%= form_for [:admin, @article], html: {multipart: true} do |form| %>
    <%= render partial: 'form', locals:{f: form} %>
    <%= form.submit %>
  <% end %>
</div>

app/views/spree/admin/blog/configuration.html.erb
<%= form_for [:admin, @configuration], method: :post do |f| %>
  <% @configuration.options.to_hash.each do |key, option| %>
    <%= label_tag "blog_configuration[options][#{key}]", key %>
    <%= custom_input_field f.object.type_of_field(key), "blog_configuration[options][#{key}]", f.object.options[key] %>
  <% end %>
  <%= f.submit :send %>
<% end %>

app/views/spree/admin/blogs/index.html.erb
<table class="table" id="listing_articles">
  <thead>
    <tr data-hook="admin_blog_index_headers">
      <th><%= Spree.t(:title) %></th>
      <th><%= Spree.t(:created_by) %></th>
      <th><%= Spree.t(:article_available_on) %></th>
      <th><%= Spree.t(:category) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @collection.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.get_author_name %></td>
        <td><%= article.available_on %></td>
        <td><%= article.get_category_name %></td>
        <td class="actions actions-3 text-right">          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/articles/index.html.erb
<% @articles.each do |article| %>
<p><%= link_to article.title, blog_article_path(slug: article.slug) %></p>
<% end %>

app/views/spree/articles/show.html.erb
<%= @article.get_content_safe(self) %>
<%= @article.title %>

app/views/spree/blog/articles/show.html.erb
<%= @article.body_html.html_safe %>
<%= @article.title %>

app/views/spree/travel_app/admin/config_gem/configuration.html.erb
<% form_for [:admin, @configuration] do |f| %>
  <% @configuration.options.to_hash.each do |key, option| %>
    <%= f.text_field f[:configuration][key] %>
  <% end %>
<% end %>

app/views/spree/travel_app/admin/config_gem/index.html.erb
<% form_for @configuration do |f| %>
  <% @configuration.options.to_hash.each do |key, option| %>
    <%= f.text_field f[:configuration][key] %>
  <% end %>
<% end %>